### ISSUE TITLE
Drawing Text not working on EAS production build

### ISSUE THREAD

**Issue by baochungit** [expo/expo-2d-context#41]
Using the code as in example, I see the text showing well on Expo Go but disappeared when trying with the standalone built by EAS. I don't know if the issue is from Expo2dContext or GLView.

```
"expo": "^45.0.0",
"expo-gl": "~11.3.0",
"expo-2d-context": "0.0.3"
```
It's tested on my Android phone: Samsung Note 10 Plus

**Comment by quirax-lee** [comment]
Did you solve the problem?
