### ISSUE TITLE
onContextCreate not called when debugger is open.

### ISSUE THREAD

**Issue by evanram** [expo/expo-2d-context#8]
Tested with the external React Native Debugger as well as default one that opens in Chrome.

`onTouchStart` triggers the alert "touch start" always, so I know that `GLView` exists in React's tree. However `_onGLContextCreate` does not seem to be called (_only when using debugger_) as the alert "created context" does not appear in debug mode.

Here is a class that demonstrates the bug:

```javascript
class TestDummy extends React.Component {
  constructor(props) {
    super(props);
    this._onGLContextCreate = this._onGLContextCreate.bind(this);
  }

  render() {
    return <GLView
              style={{ flex: 1 }}
              onContextCreate={this._onGLContextCreate}
              onTouchStart={(e) => alert('touch start')}
           />;
  }

  _onGLContextCreate(gl) {
    alert('created context');
  }
}
```

**Comment by naclomi** [comment]
Thanks for reporting this issue, Evan. Because it is a bug in Expo's underlying GLView component, could you please re-report it over at the Expo client repository (https://github.com/expo/expo) ?
